services:
  eatools:
    image: eatools
    build:
      context: .
      dockerfile: Dockerfile.dev
    command: ["npm", "run", "dev", "--", "--host"]
    environment:
      NODE_ENV: development
    ports:
      - 3000:3000
    volumes:
      - .:/app
      - /app/node_modules
    depends_on:
      - backend
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "5001:5001"
      - "5678:5678"
    volumes:
      - ./backend:/app
    command: ["python", "-m", "debugpy", "--listen", "0.0.0.0:5678", "main.py"]
